### ISSUE TITLE
ROM占用

### ISSUE THREAD

**Issue by gaojingqi23** [mysterywolf/rt_vsnprintf_full#2]
用这个的话ROM一下多了10KB，是我哪个宏没改吗

**Comment by mysterywolf** [comment]
https://github.com/mysterywolf/rt_vsnprintf_full/blob/master/rt_vsnprintf.c#L69 文件中有一些裁剪的宏 看着不需要的可以关掉~

**Comment by gaojingqi23** [comment]
开发工具：MounRiver Studio
MCU:CH32V307
工具链：GNU MCU RISC-V GCC (riscv-none-embed-gcc)（与RT-Thread Studio一致）
RTT版本：lts-v3.1.3
我的需求：打印浮点
启用rt_vsnprintf_full前ROM占用情况：
![image](https://user-images.githubusercontent.com/65592106/211453735-30f5ca53-468f-47ef-b992-b005f5d2af0b.png)
启用并裁剪后：
![image](https://user-images.githubusercontent.com/65592106/211454106-67bb837a-aa42-49a9-8a76-211020b63802.png)
ROM多了8KB，与裸机环境下实现浮点打印的6.11K相差不多，可以接受。
这个问题可以关闭了。但是当使用RT-Thread时，不仅rt_vsnprintf_full浮点打印全0.000000，而且裸机下的浮点打印方法在RT-Thread也失效了，这个问题待会会再开一个issue向您请教。

**Comment by gaojingqi23** [comment]
> 开发工具：MounRiver Studio MCU:CH32V307 工具链：GNU MCU RISC-V GCC (riscv-none-embed-gcc)（与RT-Thread Studio一致） RTT版本：lts-v3.1.3 我的需求：打印浮点 启用rt_vsnprintf_full前ROM占用情况： ![image](https://user-images.githubusercontent.com/65592106/211453735-30f5ca53-468f-47ef-b992-b005f5d2af0b.png) 启用并裁剪后： ![image](https://user-images.githubusercontent.com/65592106/211454106-67bb837a-aa42-49a9-8a76-211020b63802.png) ROM多了8KB，与裸机环境下实现浮点打印的6.11K相差不多，可以接受。 这个问题可以关闭了。但是当使用RT-Thread时，不仅rt_vsnprintf_full浮点打印全0.000000，而且裸机下的浮点打印方法在RT-Thread也失效了，这个问题待会会再开一个issue向您请教。

补充：
改为8字节对齐后，rtt下printf也可以打印浮点了，ROM占用也是8KB,较裸机下多了2KB，但和rt_vsnprintf_full一样都是8KB。最后再次感谢大佬，大佬强的！👍

**Comment by mysterywolf** [comment]
感谢提供测量数据！
