### ISSUE TITLE
rt_vsnprintf_full浮点输出全0问题

### ISSUE THREAD

**Issue by gaojingqi23** [mysterywolf/rt_vsnprintf_full#3]
开发工具：MounRiver Studio
MCU:CH32V307
工具链：GNU MCU RISC-V GCC (riscv-none-embed-gcc)（与RT-Thread Studio一致）
RTT版本：lts-v3.1.3
我的需求：打印浮点
rt_vsnprintf_full宏开关裁剪
`
/*%f %F*/
#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1
/*%e, %g, %E, %G*/
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
/*浮点精度*/
#define PRINTF_DEFAULT_FLOAT_PRECISION  6
/*最大整数长度*/
#define PRINTF_MAX_INTEGRAL_DIGITS_FOR_DECIMAL 9
/*long long类型*/
#define  PRINTF_SUPPORT_LONG_LONG 0
`
主线程
`
int main(void)
{
    rt_kprintf("rt float:%f\r\n",1.2);
    return 0;
}
`
控制台输出结果：
![image](https://user-images.githubusercontent.com/65592106/211457923-dfeb634c-1e56-4379-af5d-f0c6d4c9d41d.png)
浮点打印失败。
kservice.c里的rt_vsnprintf已经加上了RT_WEAK限定。

RT_WEAK rt_int32_t rt_vsnprintf(char       *buf,
                        rt_size_t   size,
                        const char *fmt,
                        va_list     args)
而，之前裸机可以用的printf输出浮点也失效了（不管用没有rt_vsnprintf_full都失效了）

**Comment by mysterywolf** [comment]
你把main线程的栈 栈对齐到8字节 而不是4字节试试

**Comment by gaojingqi23** [comment]
main线程是rtt动态创建的，8字节对齐是要我手动将main线程改为静态吗？

**Comment by mysterywolf** [comment]
或者改成rt_kprintf("rt float:%f\r\n",1.2f); 试一下

**Comment by mysterywolf** [comment]
你没有裁剪默认状态也全0？

**Comment by gaojingqi23** [comment]
> 或者改成rt_kprintf("rt float:%f\r\n",1.2f); 试一下
结果是这样的
![image](https://user-images.githubusercontent.com/65592106/211462705-1afb3ccf-be35-43b5-948e-c98864dab7be.png)

**Comment by gaojingqi23** [comment]
> 你没有裁剪默认状态也全0？

没有裁剪也是全0

**Comment by mysterywolf** [comment]
嗯 你把线程栈对齐到8字节就好了，C语言如果不加f 默认的是double类型，如果栈不对齐到8字节会出问题。 这个在任何平台 任何RTOS都是一样的。https://blog.csdn.net/u013073067/article/details/106537828

**Comment by gaojingqi23** [comment]
> 嗯 你把线程栈对齐到8字节就好了，C语言如果不加f 默认的是double类型，如果栈不对齐到8字节会出问题。 这个在任何平台 任何RTOS都是一样的。https://blog.csdn.net/u013073067/article/details/106537828
谢谢，我把rtconfig.h的RT_ALIGN_SIZE   改为8就可以了
#define RT_ALIGN_SIZE   8
![image](https://user-images.githubusercontent.com/65592106/211463573-a720f33d-410f-4c6d-b39a-3a15b1758f12.png)
感谢🙂

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/6842
我们已经全都改成默认8字节对齐了，后续应该就不会出现这个问题了
